### ISSUE TITLE
make flag smaller on medium sized devices

### ISSUE THREAD

**Issue by jpuck** [razorbacks/style#12]
https://stackoverflow.com/a/9017171/4233593

```css
@media (max-width: 990px) {
    .navbar {
        margin-top: 89px;
    }
}
```
